# Generated by Django 4.2.1 on 2023-08-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0003_create_vote_closingvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_profile',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
