# Generated by Django 4.2.1 on 2023-08-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0004_alter_profile_image_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='choose_option',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
